### PR TITLE
Us018 add variable dates data

### PR DESCRIPTION
**Pull request by emilioward**
This PR is associated with US018 for loading variable event dates.

**Use this to load in the variable data for the PR on Response operations UI.**

Changed the loading of CSV's so that all the details are loaded from one file rather than multiple.

Added and changed details in the CSV to reflect the CSV spreadsheets provided by the business.

### CODE REVIEW

**Review by benjefferies — CHANGES_REQUESTED** [review]
👍 Looks good but I think this breaks ras-integration-tests
We should fix them before merging.

```
Failing scenarios:
  acceptance_tests/features/view_collection_exercise_details.feature:14  View collection exercise events
  acceptance_tests/features/view_collection_exercises_data.feature:9  View attributes for a survey
```

**Comment by emilioward** [comment]
@benjefferies i've fixed the integration tests and got them all passing, could you give this another go?

**Comment by emilioward** [comment]
[US018: INT Load variable event dates for a collection exercise [M]](https://trello.com/c/n4uTwf2f/43-us018-int-load-variable-event-dates-for-a-collection-exercise-m)

**Review by tej99 — APPROVED** [review]
I preferred the csv files broken down by survey. But everything looks good 👍

**Review by andrewmil — APPROVED** [review]
Looks like this all works with the other PR's :+1:

I preferred having the data is separate files per collection exercise but this way is fine too

**Comment by andrewmil** [comment]
@benjefferies This PR works in conjunction with Emilio's [other PR](https://github.com/ONSdigital/ras-integration-tests/pull/44) in the integration tests repo. It'll work with them

**Review by benjefferies — APPROVED** [review]

**Pull request merged**
