### PR TITLE
Fix/updating mbs ce reference periods from 6 to 4 digits

### PR DESCRIPTION
**Pull request by pricem14pc**

### CODE REVIEW

**Review by JamesGardiner — COMMENTED** [review]
Is this still needed?

**Review by andrewmil — APPROVED** [review]
:+1:

**Comment by benjefferies** [comment]
@pricem14pc can we close this?

**Review by madeye-matt — APPROVED** [review]
LGTM

**Review by JamesGardiner — APPROVED** [review]

**Pull request merged**
